### ISSUE TITLE
Use something like bookdown?

### ISSUE THREAD

**Issue by dmadisetti** [nglaeser/crypto-glossary#6]
Sorry I'm creeping on your notes but I think they're super nicely done! Congrats!

I think you could, however, add another level of production value if you used something like [bookdown](https://bookdown.org/thea_knowles/dissertating_rmd_presentation/) or just [mkdocs](https://squidfunk.github.io/mkdocs-material/reference/abbreviations/).

Anyway, feel free to take it or leave it. I have a mkdocs for my notes, which links to papers and has zotero integration and is wholly doing the most (if only I spent as much time writing as optimizing my workflow right), and I love it. Jus thought I'd spread the good word.

**Comment by nglaeser** [comment]
Haha thank you! It mostly helps me organize my own thoughts, but they're public in case they happen to help anyone else out as well :)

I appreciate the suggestion! I've been meaning to upgrade the medium of the glossary since GH markdown can be quite a pain so I'll definitely keep these in mind for once I finally get around to that :P
I'd also be curious to see your notes workflow -- is it in a public repo somewhere?

**Comment by dmadisetti** [comment]
I do not, since I have papers and preprints checked into source control. I'm big on mkdocs though here's  some semi-public examples I have:

- https://baltimoreblacktechies.github.io/100daysOfCode-2021/
- https://dmadisetti.github.io/pd3
- https://dmadisetti.github.io/drt

**Comment by nglaeser** [comment]
closed by 87c460682eb930ccf1a205c3eee8d68195a9a863

**Comment by dmadisetti** [comment]
Wow @nglaeser it looks amaazing

**Comment by nglaeser** [comment]
Thank you!! :)
